# profiles.yml
airbyte_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: host.docker.internal
      port: 9131
      user: postgres
      pass: postgres
      dbname: training_db
      schema: public